stages:
  - build

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  IMAGE: $CI_REGISTRY_IMAGE

services:
  - docker:27.5-dind

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

buildimg:
  stage: build
  script:
  - docker build -t $IMAGE:latest .
  - docker push $IMAGE:latest
  tags:
  - docker