{
 "title": "Network traffic monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(texporter_captured_bytes_total,instance)"
    }
   },
   { "name": "ds", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Outgoing traffic top 10 for past 5 days",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, \n  sum by (dst) (\n    increase(texporter_captured_bytes_total{src=\"local\", dst!=\"local\",instance=\"$host\"}[5d])\n  ) / 1024^3\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming traffic top 10 for past 5 days",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, \n  sum by (src) (\n    increase(texporter_captured_bytes_total{dst=\"local\", src!=\"local\",instance=\"$host\"}[5d])\n  ) / 1024^3\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "irate(texporter_captured_bytes_total{instance=\"$host\"}[$__interval])*8/10^6",
     "legendFormat": "{{src}} -> {{dst}}"
    },
    {
     "expr": "sum(irate(texporter_captured_bytes_total{instance=\"$host\"}[$__interval])*8/10^6)",
     "legendFormat": "Total Bandwidth"
    }
   ]
  }
 ]
}