name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    defaults:
      run:
        shell: bash
        working-directory: /texporter
        
    runs-on: ubuntu-latest
    container:
      image: golang:1.23-alpine3.21
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - 
        name: Install deps
        run: |
          apk add --no-cache libbpf-dev clang llvm make linux-headers git 
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}